version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySecureRootPass123!
      MYSQL_DATABASE: phpmyadmin_db
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: MySecurePmaPass456!
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - "7070:80"
  nginx-config:
    image: alpine:latest
    volumes:
      - ./nginx.conf:/nginx.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "cp -f /nginx.conf /sites-available/pma-db.serp24.online &&
             ln -sf /etc/nginx/sites-available/pma-db.serp24.online /sites-enabled/pma-db.serp24.online &&
             ls -l /sites-enabled/pma-db.serp24.online &&
             nginx -t && systemctl restart nginx|| echo 'NGINX test failed'"
    # Runs once and exits
volumes:
  db_data: